RegisterServerEvent("sv:one")
AddEventHandler("sv:one", function(input, time)
    TriggerClientEvent('chatMessage', -1, "^1[MISSIONS]: ^2".. input .."^0 has been launched.")
    TriggerClientEvent("mt:missiontext", -1, input, time)
    TriggerClientEvent('missionBlips', -1, input)
end)
RegisterServerEvent("sv:two")
AddEventHandler("sv:two", function(message)
    TriggerClientEvent('chatMessage', -1, message)
end)